language: node_js
node_js:
- '6'
cache: yarn
deploy:
  provider: npm
  email: apstukalin@gmail.com
  api_key:
    secure: a0SBa50FrUPALmuWdhHGdntTs6RpdkY2dB6j/zkkNol42n8p06SRQw8jK/TuBoOKKtpxPVy5ygWGq80Nezn5zEUo00PXW0JWG50BJVbnWo+DLq2l9l/ZxqEkP2z6RGfFBvfcwxlxmSKmPlnZUBb/4Ehj/e0KxHA1uk76lzR/NfJHEqOFFlImJlCXzaE//383ByDjEzLun27DSToA2VjoWm67akeTcnkGZVRKvzsTaFUyrNyZPTtxAm3+6plU8G4hxQqDLWpObyBB+Ng42Ktfhqb1N1R4tJqgXqQUIaBJQVBSrq4u1fjRmDZrokcKEps/0gmPELklinU/3xO/OUeOUuDanDr08X64Wm8NwEjnn1ALUSGzBc4LQvlurhF0ys8TGfMZB7Yi8+yaNUuvGt1i6VjMKSxzd8I3tpoKzKTpr7oNvhCIuvYzel/1pMKn2bQG+yZWNheVkiRaB1EvRS6wvNYx2i0Hx5hAC0ZeUhPX1dmWEnnHDh/8tfLxpB+S8JVplHcKRA/F9a29ddCe9eec86w8Emayd1FGJtWu3JMKTfHPDT05qe3ZsEjG7zoNh0V/d0WL0rszOlPYtf+NB7l53cGTgKu5erOSBabdc2y6GG0SjTW9y3VCQZ+6dYq7I8fbriKl6c4KESIq4QhVam5FVyxD9lmAvlG/DPB1hv62bbQ=
  on:
    tags: true
    repo: HospitalRun/hospitalrun-dblisteners
  skip_cleanup: true
