language: node_js
node_js:
- '6'
cache: yarn
deploy:
  provider: npm
  email: apstukalin@gmail.com
  api_key:
    secure: lj7mznwu7l76BRFvFcGS2TO6NFZWvopUbjDAs5tv4ZU67snaQGu1aW1lNJkQlS5tB3Uzg0kV1s3OMsE/NAUuI/wPDeUih822zHbsKiP1FLqkaT9yyiVbvGEWrTpDUUKoIqmKOm7QADMy+59JpmGwFA49UFYc7sHExUUce7PFQZOOiVqihSUQS+dv8cUc5jPd86J8nKnNXAfWpUeN+E1A5SzD6FgVa7MFkbLcMa7dEm6lv/eHuBId5Fj3AIuKdKtHdoKA+vH66trUKwK7nLURaZBxILsey6LqltqAwgTPb7Ol5M1IIHgQ84Uq4NVl0/s7TEc1R6QgCXi5bdjWwaY5lQZ7W4tXJCamvrggoC2hbQ74uqpb7EUQtXVbn7iAzKtjyery9bG1i1vujLW8BWAdvRjxQhGT2+AjidRVTqcxhywcIRjrkpkKho/QcutmYMwKWN/X2SWmtMrUwNSB775apcqbMowJf1risdDxm7cvtGpPWMvhYtyhY/6ZzxMufwJ5HTEL6spVWxSfRZcDhbqN1z17OFrTqyfmGm1PnK8tyIRlm/Wo8tMTiUuQRMspdrwJ1S63bslQxZVkRXmnTy81sbpay1LVlCTrv/n0ce57zXec+6IEG5vuan0CygEOGvhk+XUZRB0XZz4g/6MBdvgwd1Lt735xfhdg8cguRLVVK4w=
  on:
    tags: true
    repo: HospitalRun/hospitalrun-dblisteners
  skip_cleanup: true
