language: node_js
node_js:
- '6'
cache: yarn
deploy:
  provider: npm
  email: apstukalin@gmail.com
  api_key:
    secure: ICR/ibCReGy9JW2eSbZ6eCPgkZuoVA8mCJAsPwQN+ONSBOuILp3x9WqIlziQHoRFQ8LwB3Q6bcZ35qZYlmDWLhPSnTpEdvJYxj0dXWJSHH7+8vKUxFaBxbA+/LOvXzLmD4gBJnqQ3ZVrKxDwLEl4fmLN1GTfDrCT84iCNhGTZH06Cswy4bla13I02xdsqp8pNcPl37Q/2/k0KzsbFXxIr5j0eF7HiOFzAin3S41bIWCTT6tFDG7ruvLS1mm+R07OjxkvsQnNcoe4UpVZO7VegosSu625TeimwbiGVzmhadGMi2Zi+g+mLhzx8CCoWSa9oZmYVBbf2BGnq7xJiq2iCZhuxbu5lvvSSBJKG9asUSRyZyXe59EZNxGe2zE809JagXQ+ooHY7zzX54bQlukZLRgb/kprBfBZs95zjw3/wCLGXWnJw8pPtiqCaEMNCasoQK6rJZOP72ruCj5qtBzKUWFVw1JmPGW6py5c5a40Lyff1E+ogAtNTnF/ANacp+o1+tZyyqm9mPwUM8l3y4+QS9IgxVG2N27tUphP0IBujLEtHGF9TGOa3ZYmmsR4bOneqjp0QCQacM6soYfZ4oJcebHY9ICuNBF6c7BEPsK+tDnEyw2j994D6fHiOsyNR7bUyifsB95Xt10TG8sIVDL47yy2Z+DGj/cD6co9+q2keuw=
  on:
    tags: true
    repo: HospitalRun/hospitalrun-dblisteners
