language: node_js
node_js:
- '6'
cache: yarn
deploy:
  provider: npm
  email: apstukalin@gmail.com
  api_key:
    secure: Ql1az5i0Q/OadbRhr5tlkkOFYKUxH0WGYFYKzOfEtFbVGA1CHaQ7eoZAmclirFJrHX8y4Rw8yhlanMXyhZEPJpSBsRCNFmydTI6avmCCHq2ZB9ykpWJhXq5yNL3cKyLCJEbNpVwoWHbMPUu7MxHviUEpA0yUU/p/W43OaIYlSVxWzxWYzRJ5/ii4T2AhjdYJfq24VHW9nTe2CYGjtlQHx8vQ03/L4QOo6SuonOanuwETeyl2MSgrtG6A9eYQGaXL7l+GCZThG6Np/nW8AUlR2ABdtZ5F6J55209CtuoeI95Ip2Son6HWf7vhDvExHuSKxIAND1iIUa1QSoI+gXAhto1Y0C8HAy5eUCxEEywXza9AyaYsn8lYIp/gQNMpqqiSPHpOsNNBbAA4LBojf9iPPYh8G0ZOUNZDjNdepEtxwj02npPqrW4QUuNdbiWGfftz91lOvHuFdZld+PYhuMjTkZ4iRZt5hsKMeOEmfWREs22woK9tO1uc1v7dK8782CtzJyw+Z8sJ9ofVvPK1m2gbxH59ECIapjzgyvdU/0M6gAh8P2NH3PYLvmGUyYhETYWTRYwhRSlBYJNoiG23khhX7Z/4RvsSVp17+Ohm4mC9ipn4fSdmXVnsmtmPyoCHJc/152SRySmjOzoThmJ7yYoQrttX03FyzG6pfdspZwyFDYI=
  on:
    tags: true
    repo: HospitalRun/hospitalrun-dblisteners
env:
  secure: IapQeLKKXDNP/HLQIA7LQ0Ph6PXM4HqrG6jr4vYn0v+GtBwyoQo+OcAKHGTkevFOPiZfi/vWt0wAlS/+tRSa4EesKtEjOAkDKLh6vlSLuK7Et8woG2xs3XMPfj7fH0CHLJF5XjWX8nZg5yTPl/T/S9wxb94K/wF97P59Vzq06NFvTzV3ToVbMA0VQw3fAqYHmQUOp4FALng+b+KLtolfszm01RAapAxu6ATPWdWe/9azxVMsi64jjRqeDNCuBJwH27vGb2QLem4SI+fCiOnvFKntaU3OPtQPvpZCLSMt8hX88iJWwFKKW+NXla5d0s/e+lv7IB/rk3dlXe9Ll86Jq8NduFdPap0DzzbucJRem1gdy3pDYhoatQPizBjbUbOU75yCxei2tm/cT/ZlfhY5VmArtr1+GGdEMNBNfCc5i4Blm14OBmlQXKwpo3jv7X1NumzoL2ACFAI6uFeljY9jCGapBHuY4eRZDncjNNdwlWL0tVBH8B+ng6keOhTn+cd3s1cQnxcJg2tzm4r8RZJQEpk0J4t9ga7+ykkxxS+gkvnR5ltdjxe83L4apsE3XVmpr4HhUhd2l5DnYAcGEOAScjnE2VfS3qr2uCp0YUTyBc3kO2qBwCh1xHTEK3UtHYNHgmVpGmF5BxnqrvtSVjaFD9cgaoabzsDGBpQalxRPcv4=
